### ISSUE TITLE
博客进入报错

### ISSUE THREAD

**Issue by crithes** [Lewage59/Lewage59.github.io#1]
报错信息：app.529cdb9e.js:49 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

**Comment by Lewage59** [comment]
> 报错信息：app.529cdb9e.js:49 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

已知问题，暂时没有维护了，可以直接看 markdown
